name: Add Timestamp File

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  create-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create timestamp file
        run: |
          mkdir -p Assets
          echo "$(date)" > Assets/timestamp.txt
          cat Assets/timestamp.txt  # Debugging: Show file content

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "Assets/timestamp.txt"
          message: "Automated commit: Adding timestamp file"
          push: true # Ensures the commit is pushed to the repo
